### ISSUE TITLE
Known replies appear as ordinary notes

### ISSUE THREAD

**Issue by LanaCoyote** [kylewm/woodwind#33] opened 2015-08-19 11:38 UTC
Reply posts in Known show up as if they were just ordinary notes in Woodwind (without an "In reply to..." link above them).

How replies from Known appear on Woodwind:
![Known reply on Woodwind](http://i.imgur.com/rcsd73E.png)

How replies appear on Known:
![Known reply](http://i.imgur.com/9MfGyXU.png)

How replies from Redwind appear:
![Redwind reply on Woodwind](http://i.imgur.com/4i6zDwi.png)

Sorry if this is a problem with Known and not Woodwind, but the reply link is properly tagged as u-in-reply-to, so I figured it was a parsing issue.

**Comment by karadaisy** [comment] 2015-08-19 13:22
Are you subscribed to the rss feed or the h-feed for those sources? At least for my site, it looks like the latter (which does not have a u-in-reply-to property).

**Comment by karadaisy** [comment] 2015-08-19 13:25
Here's how that post looks to me ![tmp_15727-screenshot_2015-08-19-07-20-55-1671055914](https://cloud.githubusercontent.com/assets/950127/9357306/74356760-4643-11e5-9338-44f23a16dc94.png)

**Comment by karadaisy** [comment] 2015-08-20 00:36
I just confirmed that you are subscribed to my Atom feed and Ben's RSS feed -- To my knowledge, legacy feeds don't support in-reply-tos, so there's no way for Woodwind to recognize them. 

I'm closing, but feel free to re-open if you disagree!

**Closed as completed by karadaisy** 2015-08-20 00:36 UTC

**Comment by LanaCoyote** [comment] 2015-08-20 11:19
Yeah, the problem was with using RSS feeds. Maybe a blurb on the subscribe-to modal that mentions that legacy feeds don't support microformats markup?
